name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1

    - name: "Setup"
      run: |
        cp .github/.bazelrc.local .

    - name: "toolchain-arm64-gcc"
      run: |
        cd toolchain-arm64-gcc
        ../.github/bazel build ... --platforms=toolchain_arm64_gcc

    - name: "toolchain-arm64-gcc-docker"
      run: |
        cd toolchain-arm64-gcc-docker
        ../.github/bazel build ... --platforms=toolchain_arm64_gcc_docker
